### PR TITLE
Adding default post processor option

### PR DESCRIPTION
**Pull request by philippe-randour**
This PR addresses the need for a custom processor.

### CODE REVIEW

**Comment by KKSzymanowski** [comment]
I'm currently on a vacation so I can't test this but what happens if the config entry for the processor is empty or not provided?

**Comment by philippe-randour** [comment]
You are right, I have added a default class in this case.

**Comment by KKSzymanowski** [comment]
I can merge this into master so you can use "dev-master" version in composer to see this. When I get back, by the end of August, I'll test this out and release a new version.

**Comment by KKSzymanowski** [comment]
I have documented the new feature in the readme.md file and released a new 6.0.3 version.

**Pull request merged**
